AWSTemplateFormatVersion: 2010-09-09
Description: "Recursos Default IAM"

Resources:
  GrupodeUsuarios:
    Type: AWS::IAM::Group
    Properties:
        GroupName: HSBS
        ManagedPolicyArns: 
          - arn:aws:iam::aws:policy/AdministratorAccess
  
  UsuarioFelipe:
    Type: AWS::IAM::User
    Properties:
      UserName: hsbs.felipe
      Path: /
      Groups:
        - HSBS

  UsuarioReivson:
    Type: AWS::IAM::User
    Properties:
      UserName: hsbs.reivson
      Path: /
      Groups:
        - HSBS

  UsuarioAdmin:
    Type: AWS::IAM::User
    Properties:
      UserName: hsbs.admin
      Path: /
      Groups:
        - HSBS
        
  RoledeAcessoCondicional:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "datacenter-management"
      Description: "Asssuming hole as admin from HSBS account."
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/PowerUserAccess     
      MaxSessionDuration: 7200
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": "arn:aws:iam::036544166405:root"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                    "Bool": {
                        "aws:MultiFactorAuthPresent": "true"
                    }
                }
            }
        ]
      }